{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61Z628.jpg' text='' width='415' height='248'} /uploads/allimg/150906/1-150Z61Z628.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61Z631.jpg' text='' width='415' height='248'} /uploads/allimg/150906/1-150Z61Z631.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61Z633.jpg' text='' width='415' height='248'} /uploads/allimg/150906/1-150Z61Z633.jpg {/dede:img}
