<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150906/1-150Z61Z628.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z628.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="415";
$z[1][4]['height']="248";
$z[2]=Array("img"," /uploads/allimg/150906/1-150Z61Z631.jpg ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z631.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="415";
$z[2][4]['height']="248";
$z[3]=Array("img"," /uploads/allimg/150906/1-150Z61Z633.jpg ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z633.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="415";
$z[3][4]['height']="248";

?>