{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61RT5.png' text='' width='415' height='248'} /uploads/allimg/150906/1-150Z61RT5.png {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61RT7.png' text='' width='615' height='385'} /uploads/allimg/150906/1-150Z61RT7.png {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z61RU6.png' text='' width='424' height='248'} /uploads/allimg/150906/1-150Z61RU6.png {/dede:img}
