{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6215918.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6215918.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6215921.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6215921.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6215924.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6215924.jpg {/dede:img}
