
<field:showusername itemname="昵称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:showusername>

<field:showusertel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:showusertel>

<field:showemail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:showemail>

<field:showcontent itemname="留言板" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:showcontent>
