
<field:i-company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-company>

<field:i-name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-name>

<field:i-phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-phone>

<field:xyfw itemname="需要的服务" autofield="1" type="checkbox" isnull="true" default="现有网站改版,现有网站进行营销推广,建设全新的企业网站,要找长期合作公司，需要年度服务"  maxlength="250" page="">
</field:xyfw>

<field:gzdf itemname="关注的地方" autofield="1" type="checkbox" isnull="true" default="对功能要求比较高,对设计创意要求比较高,需要可以购物支付,搜索引擎排名"  maxlength="250" page="">
</field:gzdf>

<field:cbys itemname="预算" autofield="1" type="checkbox" isnull="true" default="3万以内,3-5万,5-10万,10万以上需招投标"  maxlength="250" page="">
</field:cbys>
