<li class="Core"> <img src="webimages/index_326.jpg" alt="[field:typename /]" width="293" height="250">
        <h3><a href="[field:typelink /]">[field:typename /]</a></h3>
        <div class="CoreBusinessbox">
          <h4><a href="[field:typelink /]"></a></h4>
		  <p><a href="[field:typelink /]">随着移动设备的普及，通过移动设备进行浏览，购物，查询的消费者越来越多。移动设备具有随时随地的进行交互的便利性，结合硬件的GPS定位能力，能够更好的提供精确服务。</a></p>
        <a class="cr_index_more" href="[field:typelink /]"></a> </div>
      </li>