<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1175,1210);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1487,1658);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";
$z[4]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" width=\"292px\" height=\"220px\" alt=\"[field:title /]\">\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n          ",8036,8309);
$z[4][4]['row']="4";
$z[4][4]['typeid']="1";
$z[4][4]['titlelen']="20";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("include","",8423,8463);
$z[5][4]['filename']="tanchuang.htm";

?>