<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,173);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",213,265);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",996,1031);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1142,1161);
$z[5][4]['name']="title";
$z[6]=Array("field","",1176,1228);
$z[6][4]['name']="description";
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("prenext","",1265,1290);
$z[7][4]['get']="pre";
$z[8]=Array("prenext","",1295,1321);
$z[8][4]['get']="next";
$z[9]=Array("field","",1335,1354);
$z[9][4]['name']="dizhi";
$z[10]=Array("field","",1363,1382);
$z[10][4]['name']="title";
$z[11]=Array("productimagelist","\r\n		  <li><img src=\"[field:imgsrc/]\"></li>\r\n		  ",1759,1854);
$z[12]=Array("field","",1936,1954);
$z[12][4]['name']="body";
$z[13]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" width=\"292px\" height=\"220px\" alt=\"[field:title /]\">\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n		  ",2360,2621);
$z[13][4]['row']="4";
$z[13][4]['typeid']="1";
$z[13][4]['titlelen']="20";
$z[13][4]['orderby']="pubdate";
$z[14]=Array("include","",2719,2759);
$z[14][4]['filename']="tanchuang.htm";

?>