
<field:i-company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-company>

<field:i-name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-name>

<field:i-phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:i-phone>

<field:xyfw itemname="需要的服务" autofield="1" type="checkbox" isnull="true" default="现有网站改版,现有网站进行营销推广,建设全新的企业网站,要找长期合作公司，需要年度服务"  maxlength="250" page="">
</field:xyfw>
