<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150906/1-150Z61Z312.png ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z312.png";
$z[1][4]['text']="";
$z[1][4]['width']="615";
$z[1][4]['height']="385";
$z[2]=Array("img"," /uploads/allimg/150906/1-150Z61Z315.png ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z315.png";
$z[2][4]['text']="";
$z[2][4]['width']="415";
$z[2][4]['height']="248";
$z[3]=Array("img"," /uploads/allimg/150906/1-150Z61Z317.png ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z317.png";
$z[3][4]['text']="";
$z[3][4]['width']="415";
$z[3][4]['height']="248";
$z[4]=Array("img"," /uploads/allimg/150906/1-150Z61Z321.png ",528,671);
$z[4][4]['ddimg']="/uploads/allimg/150906/1-150Z61Z321.png";
$z[4][4]['text']="";
$z[4][4]['width']="415";
$z[4][4]['height']="248";

?>