<div class="zhongbiaoli">
          <dl>
            <dt><a href="[field:arcurl/]" title="[field:title /]"><img src="[field:picname/]" alt="[field:title /]" width="348" height="258"></a></dt>
            <dd>
              <h3><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h3>
              <p><a href="[field:arcurl/]">[field:infos/]…</a></p>
            </dd>
          </dl>
        </div>