{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6220333.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6220333.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6220336.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6220336.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150906/1-150Z6220338.jpg' text='' width='247' height='439'} /uploads/allimg/150906/1-150Z6220338.jpg {/dede:img}
