<li class="cur">
        <h4><a href="[field:typelink /]">[field:typename /]</a></h4>
        <p><a href="[field:typelink /]"> 专注B2C零售销售者购物体验 </a></p>
        <p><a href="[field:typelink /]"> 全面管理，快速搭建在线商城 </a></p>
        <p><a href="[field:typelink /]"> 良好的二次开发和部署框架 </a></p>
        <p><a href="[field:typelink /]"> 企业级的高安全性和可靠性 </a></p>
      <a class="cr_index_more" href="[field:typelink /]"></a> 
	  </li>