<li class="Core"> <img src="webimages/index_325.jpg" alt="[field:typename /]" width="293" height="250">
        <h3><a href="[field:typelink /]">[field:typename /]</a></h3>
        <div class="CoreBusinessbox">
          <h4><a href="[field:typelink /]"></a></h4>
		  <p><a href="[field:typelink /]">我们强大的设计实力支撑，帮助客户跳出千篇一律的传统商城模板式网站，提升超强用户体验的感官设计，更加有利于产品及品牌展示，从而提升消费者的整个购物体验！</a></p>
          <a class="cr_index_more" href="[field:typelink /]"></a> </div>
      </li>