<?php
$z[0]=Array("channelartlist","\r\n	  <li><span><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename' /}</a></span><b></b>\r\n        <div class=\"downmenu\">\r\n          <p> \r\n		  {dede:channel type='son' noself='yes'}\r\n		  <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n		  {/dede:channel}\r\n		  </p>\r\n        </div>\r\n      </li>\r\n	  ",975,1353);
$z[0][4]['typeid']="top";
$z[0][4]['row']="6";

?>