<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,532);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1264,1299);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1570,1741);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[5][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";
$z[6]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" width=\"292px\" height=\"220px\" alt=\"[field:title /]\">\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n          ",15442,15715);
$z[6][4]['row']="4";
$z[6][4]['typeid']="1";
$z[6][4]['titlelen']="20";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",15813,15853);
$z[7][4]['filename']="tanchuang.htm";

?>