<?php
$z[0]=Array("arclist","\r\n      <li><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[签约]  [field:title /] ------------------------  [[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</a></li>\r\n      ",161,423);
$z[0][4]['row']="7";
$z[0][4]['typeid']="25";
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("channelartlist"," <a href=\"{dede:field name='typeurl'/}\">{dede:field\r\n          name='typename'/}</a> ",500,674);
$z[1][4]['row']="4";
$z[1][4]['type']="top";
$z[1][4]['typeid']="1,5,10,15";
$z[1][4]['col']="1";
$z[2]=Array("channelartlist"," <a href=\"{dede:field name='typeurl'/}\">{dede:field\r\n          name='typename'/}</a> ",693,855);
$z[2][4]['row']="4";
$z[2][4]['typeid']="20,21,22";
$z[2][4]['col']="1";
$z[3]=Array("include","",1418,1455);
$z[3][4]['filename']="footer.htm";

?>