<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1175,1210);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","<a href=\"[field:typelink /]\" class=\"dingzhi cur\"><span></span>[field:typename /]<br>网站建设方案</a>",1367,1508);
$z[3][4]['typeid']="11";
$z[4]=Array("type","<a href=\"[field:typelink /]\" class=\"chanpin\"><span></span>[field:typename /]<br>建设方案</a>",1511,1642);
$z[4][4]['typeid']="12";
$z[5]=Array("type","<a href=\"[field:typelink /]\" class=\"yidong \"><span ></span>[field:typename /]<br>网站解决方案</a>",1645,1783);
$z[5][4]['typeid']="13";
$z[6]=Array("type","<a href=\"[field:typelink /]\" class=\"weixin\"><span></span>[field:typename /]<br> 解决方案</a>",1786,1917);
$z[6][4]['typeid']="14";
$z[7]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" width=\"292px\" height=\"220px\" alt=\"[field:title /]\">\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n          ",24226,24499);
$z[7][4]['row']="4";
$z[7][4]['typeid']="1";
$z[7][4]['titlelen']="20";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("include","",24613,24653);
$z[8][4]['filename']="tanchuang.htm";

?>