<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,532);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1263,1298);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","<a href=\"[field:typelink /]\" class=\"dingzhi\"><span></span>[field:typename /]<br>网站建设方案</a>",1455,1592);
$z[5][4]['typeid']="11";
$z[6]=Array("type","<a href=\"[field:typelink /]\" class=\"chanpin\"><span></span>[field:typename /]<br>建设方案</a>",1595,1726);
$z[6][4]['typeid']="12";
$z[7]=Array("type","<a href=\"[field:typelink /]\" class=\"yidong  cur \"><span ></span>[field:typename /]<br>网站解决方案</a>",1729,1872);
$z[7][4]['typeid']="13";
$z[8]=Array("type","<a href=\"[field:typelink /]\" class=\"weixin\"><span></span>[field:typename /]<br> 解决方案</a>",1875,2006);
$z[8][4]['typeid']="14";
$z[9]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" width=\"292px\" height=\"220px\" alt=\"[field:title /]\">\r\n            <p>[field:title /]</p>\r\n            </a></li>\r\n          ",4537,4810);
$z[9][4]['row']="4";
$z[9][4]['typeid']="1";
$z[9][4]['titlelen']="20";
$z[9][4]['orderby']="pubdate";
$z[10]=Array("include","",4908,4948);
$z[10][4]['filename']="tanchuang.htm";

?>