<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1175,1210);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","\r\n		<li><a href=\"[field:typelink /]\"><img src=\"/images/index_239.jpg\">\r\n          <h3>[field:typename /]</h3>\r\n          <p class=\"wxfont14\"><span>+</span>了解更多＞</p>\r\n          </a></li>\r\n		  ",1423,1658);
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n        <li><a href=\"[field:typelink /]\"><img src=\"/images/index_240.jpg\">\r\n          <h3>[field:typename /]</h3>\r\n          <p class=\"wxfont14\"><span>+</span>了解更多＞</p>\r\n          </a></li>\r\n		  ",1664,1905);
$z[4][4]['typeid']="7";
$z[5]=Array("type","\r\n        <li class=\"cur\"><a href=\"[field:typelink /]\"><img src=\"/images/index_241.jpg\">\r\n          <h3>[field:typename /]</h3>\r\n          <p class=\"wxfont14\"><span>+</span>了解更多＞</p>\r\n          </a></li>\r\n		  ",1911,2164);
$z[5][4]['typeid']="8";
$z[6]=Array("type","\r\n		  <h3><a href=\"[field:typelink /]\">[field:typename /]</a></h3>\r\n          <p>初创品牌：帮助初创品牌落地生根，迅速成长。</p>\r\n          <p>成长品牌：帮助成长品牌实现更多商业价值，成长为龙头企业。</p>\r\n          <p>成熟品牌：帮助成熟品牌突破发展瓶颈，走向市场新格局。</p>\r\n          <span><a href=\"[field:typelink /]\"><em>+</em>了解更多＞</a></span>\r\n		  ",2258,2729);
$z[6][4]['typeid']="9";
$z[7]=Array("type","<a href=\"[field:typelink /]\">查看更多></a>",2812,2892);
$z[7][4]['typeid']="3";
$z[8]=Array("arclist","\r\n		<li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\"></a>\r\n          <h4><a href=\"[field:arcurl /]\">[field:title /]</a></h4>\r\n          <p>[field:infos/]…</p>\r\n        </li>\r\n		",2953,3237);
$z[8][4]['row']="4";
$z[8][4]['typeid']="3";
$z[8][4]['titlelen']="20";
$z[8][4]['orderby']="pubdate";
$z[8][4]['infolen']="150";
$z[9]=Array("include","",3282,3322);
$z[9][4]['filename']="tanchuang.htm";

?>