<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1175,1210);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n  <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n  ",1536,1713);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";
$z[4]=Array("type","<a href=\"[field:typelink /]\">查看更多></a>",4748,4828);
$z[4][4]['typeid']="3";
$z[5]=Array("arclist","\r\n		<li><img src=\"[field:picname/]\">\r\n          <h4><a href=\"[field:arcurl /]\">[field:title /]</a></h4>\r\n          <p>[field:infos/]…</p>\r\n        </li>\r\n		",4889,5142);
$z[5][4]['row']="6";
$z[5][4]['typeid']="3";
$z[5][4]['titlelen']="20";
$z[5][4]['orderby']="pubdate";
$z[5][4]['infolen']="150";
$z[6]=Array("include","",5796,5836);
$z[6][4]['filename']="tanchuang.htm";

?>